### ISSUE TITLE
NO limits is unreadable because of background

### ISSUE THREAD

**Issue by gedw99** [JugglerX/hugo-hero-theme#10]
https://hugo-hero.netlify.com/about/

**Comment by JugglerX** [comment]
true, its just example content. You can change the background yeah?

**Comment by gedw99** [comment]
Yeah its a great template - but i am useless at Design :) hehe

**Comment by JugglerX** [comment]
Just put a new image in the static folder and update the path in the layout. Try a bunch of different images from www.unsplash.com they are awesome and all royalty free

**Comment by gedw99** [comment]
thanks. wil try it out :)

**Comment by gedw99** [comment]
@JugglerX I had a much better idea

In the main banner for the "work" page you added a blend to the image to make it blue.
What if we do the same approach for the  images for No Limits, etc.
Basically just white it out.
Could also dake it out and make the text white.
Then the image is still there but you will always be able to read the text !

**Comment by JugglerX** [comment]
The full-width strips on the About Us page use shortcodes. This makes it flexible to add or remove as many strips as you like from within the markdown file. You can modify the shortcode templates to accept a parameter so that you can switch between a blended bg or a regular image bg. There are enough working examples in the code to add this if that is your unique need. It's probably not something I will add to the theme at this stage. Perhaps when I get time to spend a few days on the next release I will add more configuration options to these shortcodes. Thanks for your feedback!

**Comment by gedw99** [comment]
hey @JugglerX wow thats pretty slick

Can you give me a URL link to the code to show this aspect of the shortcodes and background blends ?
Sorry for being so thick. I find HUGO to be a bit of a monster of abstraction
