### ISSUE TITLE
IE 11 Rendering Issue

### ISSUE THREAD

**Issue by agiangone** [JugglerX/hugo-hero-theme#16]
Thank you for this very nice theme. First time using Hugo for me so maybe I missed something but while the demo page looks great in Chrome, I noticed that the footer shows up at the top in IE11.
I do see that the   <meta http-equiv="x-ua-compatible" content="ie=edge"> is present in the file (even though I thought it should be the first tag after <head>) and it seems that the browser reads it correctly as in developer mode (F12) under emulation, it shows Edge (Default) via X-UA compatible meta tag.

This is the page I'm referring to:
https://themes.gohugo.io/theme/hugo-hero-theme/

IE version is 11.0.9600.19403 update version 11.0.136

Thank you for your time.

**Comment by JugglerX** [comment]
I don't have IE to test with, but I'd say the most likely caused by the 100vh on .page. This makes the footer to stick to the bottom even when there is not enough content to push it down.

the css for this is 

```
.page {
    display: flex;
    min-height: 100vh;
    flex-direction: column;
}
```

Try removing the `min-height: 100vh`

Otherwise it's probably an issue with flexbox.

If you are able to fix it in IE 11 I'd gladly accept a PR.

**Comment by agiangone** [comment]
Hi Robert, I'm not much of a programmer but let me give it a shot. I'll let
you know tomorrow.
Thanks,
Andrea

**Comment by JugglerX** [comment]
No worries, its up to you. I probably wont fix the issue myself, I prefer to stick my head in the sand and pretend IE doesnt exist  >_<

**Comment by agiangone** [comment]
Hi Robert,
I'm sorry to say but that wasn't it. Personally I'm with you on IE so I'll close the issue but if anyone figures out a fix I'll try applying it.
